{
    'name': 'School management system',
    'sequence': -100,
    'application': 1,
    'author': 'Selim Reza',
    'website': 'https://www.odoo.com/app/invoicing',
    'license': 'LGPL-3',
    'version': '1.2',
    'category': 'managemental',
    'data': [
        'security/ir.model.access.csv',
        'data/student_sequence_data.xml',
        'views/menu.xml',
        'views/teacher.xml',
        'views/student.xml',
        'views/classroom.xml',
        'views/section.xml',
        'views/course.xml',
        'views/tags.xml',
    ],
    'depends': ['mail'],
}
